#!/bin/bash

git checkout master && \
  git pull origin master && \
  git checkout gh-pages && \
  git merge master && \
  bundle install --path=vendor/bundle && \
  bundle exec ./compile && \
  cp -r ./build/* . && \
  mv index.md.html index.html && \
  git add *.html assets/styles.css assets/*.png && \
  git commit -m "Deploying" && \
  git push origin gh-pages

git checkout master
