#! /usr/bin/env ruby

require 'kramdown'

#
# Make sure we have the directories
#

agreements = File.join(__dir__, "..", "agreements")
#puts agreements
unless File.exists?(agreements)
  STDERR.puts("Couldn't find the agreements directory at: #{agreements}")
  exit 1
end

build = File.join(__dir__, "..", "build")
unless File.exists?(build)
  STDERR.puts("Couldn't find the build directory at: #{build}")
  exit 1
end

html = File.join(__dir__, "..", "html")
unless File.exists?(html)
  STDERR.puts("Couldn't find the html directory at: #{html}")
  exit 1
end

content =
  File.read("#{html}/top.html") +
  Kramdown::Document.new(File.read("#{agreements}/govpress.md")).to_html +
  Kramdown::Document.new(File.read("#{agreements}/technical_terms.md")).to_html +
  File.read("#{html}/bottom.html")

File.open("#{build}/govpress_combined.html", 'w') { |f| f.write(content) }
